name: Windows Build

on:
  workflow_call:

jobs:
  build:
    # Clone the repository
    - name: Git checkout
      uses: actions/checkout@v2

    # Setup environment
    - name: Configure environment
      uses: microsoft/setup-msbuild@v1.0.2

    # Build project files
    - name: Configure Project
      run: premake5.exe vs2022

    # Build project
    - name: Build
      run: msbuild /m /p:Configuration=Release ./build/metrisca.sln
