name: Build

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Build job
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      # Do not stop other jobs if one fails
      fail-fast: false
      matrix:
        # List of config to run the build pipeline on
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            generator: "Visual Studio 17 2022"
          }
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++",
            generator: "Ninja"
          }
        - {
            name: "MacOS Latest Clang",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++",
            generator: "Ninja"
          }

    steps:
    # Clone the repository
    - name: Git checkout
      uses: actions/checkout@v2

    # Setup windows environment
    - name: Configure Windows environment
      if: startsWith(matrix.config.os, 'windows')
      uses: microsoft/setup-msbuild@v1.0.2

    # Setup Ubuntu environment
    - name: Configure Ubuntu environment
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake
        ninja --version
        cmake --version
        gcc --version

    # Setup MacOS environment
    - name: Configure MacOS environment
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew install cmake ninja
        ninja --version
        cmake --version

    # Configure project
    - name: Configure project
      shell: bash
      run: |
        mkdir build
        cmake \
          -S . \
          -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -G "${{ matrix.config.generator }}" \

    # Build project
    - name: Build project
      shell: bash
      run: cmake --build build --config Release
