name: Build

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Build job
jobs:
  build:
    strategy:
      # Do not stop other jobs if one fails
      fail-fast: false
      matrix:
        # List of config to run the build pipeline on
        config:
        - {
            build-workflow: ./.github/workflows/windows/build.yml
          }
        - {
            build-workflow: ./.github/workflows/ubuntu/build.yml
          }
    uses: ./.github/workflows/windows-build.yml