name: Ubuntu Build

on:
  workflow_call:

jobs:
  build:
    # Clone the repository
    - name: Git checkout
      uses: actions/checkout@v2

    # Setup environment
    - name: Configure environment
      run: chmod +x ./premake5

    # Build project files
    - name: Configure Project
      run: premake5 gmake2

    # Build project
    - name: Build
      run: make -C build config=release